---
# Master Playbook to Orchestrate the VM Provisioning Process

# Call Playbook for Common tasks
- import_playbook: common/common.yml

# Call Playbook for Storage Provisioning
# - import_playbook: storage-provision/storage-provision.yml

# Call Playbook for Pre-VM Provisioning work
#- import_playbook: pre-vm-provision/pre-vm-provision-manager.yml

# Call Playbook for VM Provisioning
#- import_playbook: vm-provision/vm-provision.yml

# Call Playbook for the Overbuild
# - import_playbook: overbuild/overbuild.yml

# Call Playbook for Post-VM Provisioning work
#- import_playbook: post-vm-provision/post-vm-provision-manager.yml