---
# Master Playbook to Orchestrate the VM Provisioning Process

# Call Playbook for Common tasks
#- import_playbook: common/common.yml

# Call Playbook for Storage Provisioning
- import_playbook: storage-provision/storage-provision.yml

# Call Playbook for Printing variables
- import_playbook: common/print.yml --extra-vars "var={{ datastore_creation }}"

# Call Playbook for VM Provisioning
#- import_playbook: vm-provision/vm-provision.yml

# Call Playbook for the Overbuild
#- import_playbook: overbuild/overbuild.yml