---
# Master Playbook to Orchestrate the VM Provisioning Process

# Call Playbook for Common tasks
#- import_playbook: common/common.yml

# Call Playbook for Storage Provisioning
- import_playbook: storage-provision/storage-provision.yml

# Call Playbook for Printing variables
#- import_playbook: common/print.yml --e "test=asd"
- import_playbook: common/print.yml --e '{"test":asd}'
#- import_playbook: common/print.yml --e '{"version":"1.23.45","other_variable":"foo"}'


# Call Playbook for VM Provisioning
#- import_playbook: vm-provision/vm-provision.yml

# Call Playbook for the Overbuild
#- import_playbook: overbuild/overbuild.yml