---

- hosts: localhost, all
  tasks:
  - name: Create a virtual machine on given ESXi hostname
    vmware_guest:
      hostname: "{{ host_ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      datacenter: ha-datacenter
      folder: /
      name: "{{ name_vm }}"
      state: poweredon
      guest_id: "{{ guest_id }}"
      # This is hostname of particular ESXi server on which user wants VM to be deployed
      esxi_hostname: "{{ host }}"
      disk:
      - size_gb: "{{ store_size }}"
        type: thin
        datastore: "{{ datastore }}"
      cdrom:
        type: iso
        iso_path: "[{{ datastore }}] {{ cdrom_name }}{{ cdrom_extension }}"
      hardware:
        memory_mb: "{{ memory_mb }}"
        num_cpus: "{{ num_cpus }}"
        scsi: paravirtual
      networks:
      - name: VM Network
        mac: aa:bb:dd:aa:00:14
        ip: 10.10.10.100
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy_vm