- hosts: localhost, all
  tasks:
    - name: Mount VMFS datastores to ESXi
      vmware_host_datastore:
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          datastore_name: "datastore3"
          datastore_type: "vmfs"
          vmfs_device_name: "mpx.vmhba0:C0:T0:L0"
          vmfs_version: 6
          esxi_hostname: "{{ host_name }}"
          state: present
      delegate_to: localhost
      register: datastore_creation