- name: setting auto_configuration_done control variable
  set_fact:
    auto_configuration_done: false

- name: 'Wait until success'
  block:

    - name: Make temp directory for Python virtualenv
      tempfile:
        state: directory
        prefix: vmware_guest_info.
      register: tempvenv
      delegate_to: localhost
      become: no
    
    - name: Before Installing zabbix-api
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - name: Install the zabbix-api Python module
      pip:
        name: zabbix-api
        virtualenv: "{{ tempvenv.path }}"
        virtualenv_site_packages: yes
      delegate_to: localhost
      become: no

    - name: Install the zabbix-api Python module
      pip:
        name: pyvmomi>3.7.1
        virtualenv: "{{ tempvenv.path }}"
        virtualenv_site_packages: yes
      delegate_to: localhost
      become: no
    
    - name: Gather some info in vsphere mode
      vars:
        ansible_python_interpreter: "{{ tempvenv.path }}/bin/python"
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ item.datacenter_name }}"
        name: "{{ item.vm_name }}"
        schema: "vsphere"
      delegate_to: localhost
      register: info_vsphere
      become: no

    - name: setting auto_configuration_done control variable
      set_fact:
        auto_configuration_done: true
      when: ((info_vsphere.instance.layout.logFile is defined) and (info_vsphere.instance.layout.logFile|length > 0))

    - name: Before Pause
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - pause:
        minutes: 5
      when: auto_configuration_done|bool == false

    - name: After Pause
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

  rescue:

    - debug:
        msg: "VMware Log File not detected yet"
      when: auto_configuration_done|bool == false

    - name: Print current date and time
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - include_tasks: auto-configuration-validation.yml
      when: auto_configuration_done|bool == false

- name: Success message
  debug: msg="WMware Log File detected - Provision of {{ item.vm_name }} at {{ item.datacenter_name }} is complete"

- name: Print current date and time
  debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"