- name: setting auto_configuration_done control variable
  set_fact:
    auto_configuration_done: false

- name: 'Wait until success'
  block:

    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - debug: var=username_on_the_host
    
    - pip:
        name: pyvmomi>6.7.1

    - name: Gather some info in vsphere mode
      vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ item.datacenter_name }}"
        name: "{{ item.vm_name }}"
        schema: "vsphere"
      delegate_to: localhost
      register: info_vsphere

    - name: setting auto_configuration_done control variable
      set_fact:
        auto_configuration_done: true
      when: ((info_vsphere.instance.layout.logFile is defined) and (info_vsphere.instance.layout.logFile|length > 0))

    - name: Before Pause
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - pause:
        minutes: 5
      when: auto_configuration_done|bool == false

    - name: After Pause
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

#    - name: Perform some common tasks
#      command: sh validation-pause.sh
#      register: result
#      when: auto_configuration_done|bool == false

  rescue:

    - debug:
        msg: "VMware Log File not detected yet"
      when: auto_configuration_done|bool == false

    - name: Print current date and time
      debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

    - include_tasks: auto-configuration-validation.yml
      when: auto_configuration_done|bool == false

- name: Success message
  debug: msg="WMware Log File detected - Provision of {{ item.vm_name }} at {{ item.datacenter_name }} is complete"

- name: Print current date and time
  debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"