---

- hosts: localhost
  tasks:

  - name: Make temp directory for Python virtualenv
    tempfile:
      state: directory
      prefix: vmware_guest_info.
    register: tempvenv
    delegate_to: localhost
    become: no

  - name: Install the Pyvmomi Python module
    pip:
      name: pyvmomi>3.7.1
      virtualenv: "{{ tempvenv.path }}"
      virtualenv_site_packages: yes
    delegate_to: localhost
    become: no

  - name: Gather some info in vsphere mode
    vars:
      ansible_python_interpreter: "{{ tempvenv.path }}/bin/python"
    vmware_guest_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ item.datacenter_name }}"
      name: "{{ item.vm_name }}"
      schema: "vsphere"
    delegate_to: localhost
    register: info_vsphere
    become: no