---

- hosts: localhost
  tasks:

  - name: Make temp directory for Python virtualenv
    tempfile:
      state: directory
      prefix: vmware_guest_info.
    register: tempvenv
    delegate_to: localhost
    become: no
  
  - name: Before Installing zabbix-api
    debug: msg="{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

  - name: Install the zabbix-api Python module
    pip:
      name: enum34
      state: absent
      virtualenv: "{{ tempvenv.path }}"
      virtualenv_site_packages: yes
    delegate_to: localhost
    become: no
    ignore_errors: yes

  - name: Install the zabbix-api Python module
    pip:
      name: zabbix-api
      state: latest
      executable: /usr/bin/pip
      #virtualenv: "{{ tempvenv.path }}"
      virtualenv_site_packages: yes
    delegate_to: localhost
    become: no
    ignore_errors: yes

  - name: Install the Pyvmomi Python module
    pip:
      name: pyvmomi
      state: latest
      virtualenv: "{{ tempvenv.path }}"
      virtualenv_site_packages: no
      virtualenv_python: /usr/bin/python
    delegate_to: localhost
    become: no
    ignore_errors: yes

  - name: Gather some info in vsphere mode
    vars:
      ansible_python_interpreter: "{{ tempvenv.path }}/bin/python"
    vmware_guest_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ item.datacenter_name }}"
      name: "{{ item.vm_name }}"
      schema: "vsphere"
    delegate_to: localhost
    register: info_vsphere
    become: no