---

- hosts: localhost
  tasks:

  - name: get the username running the deploy
    become: false
    local_action: command whoami
    register: username_on_the_host

  - debug: var=username_on_the_host

  - pip:
      name: pyvmomi>6.7.1
      executable: pip

  - name: Gather some info in vsphere mode
    vmware_guest_info:
      hostname: "photon-machine.localdomain"
      username: "administrator@vsphere.local"
      password: "Root718293?"
      validate_certs: no
      datacenter: "Suwanee"
      name: "INTCCM1S01DEN"
      schema: "vsphere"
    delegate_to: localhost
    register: info_vsphere
