---
# Playbook for Common Tasks

- hosts: localhost
  tasks:

  - name: Perform some common tasks
    command: sh ./behavior-mock.sh
    register: completed_common
    delegate_to: localhost

  - name: Including access users
    include_vars: access-users.yml

  - name: Including access passwords
    include_vars: access-passwords.yml