---
# Playbook for Common Tasks

- hosts: localhost
  tasks:

  - name: Include Template parameters as variables
    include_vars: vmware-vcenter-credentials.yml
    register: included_vmware_vcenter_credentials

  - name: Perform some common tasks
    command: sh ./behavior-mock.sh
    register: completed_common
    delegate_to: localhost