---
# Playbook for Common Tasks

- hosts: localhost
  tasks:

  - name: Perform some common tasks
    command: sh ./behavior-mock.sh
    register: completed_common
    delegate_to: localhost

#  - name: Include Template parameters as variables
#    include_vars: template-dev-UNOW-73.yml
#    when: (call_from_tower is undefined or call_from_tower|bool == False)
#    register: included_template_parameters