---

- hosts: localhost, all
  tasks:

  - name: include answer-file-c1-template
    include_vars: answer-file-c1-template.yml
  
  - name: Create Directory to place CUCM platformConfig.xml
    file:
      path: 'temp/{{ customer_name }}'
      state: directory
      mode: 0777
    register: "answer_files_folder"
    delegate_to: localhost
  
  - include_tasks: answer-file-passwords.yml

  - name: Delete CUCM platformConfig.xml if exists
    file:
      path: '{{ cucm_primary_node.answer_file_path }}'
      state: absent
    register: "cucm_primary_answer_file"
    delegate_to: localhost

  - name: Create CUCM platformConfig.xml
    file:
      path: '{{ cucm_primary_node.answer_file_path }}'
      state: touch
      mode: 0777
    register: "cucm_primary_answer_file"
    delegate_to: localhost

  - name: Add initial XML line
    lineinfile:
      path: '{{ cucm_primary_node.answer_file_path }}'
      line: '<?xml version="1.0"?><PlatformData></PlatformData>'
    register: "cucm_initial_line_primary_answer_file"
    delegate_to: localhost

  - name: Add a 'Version' element to the 'PlatformData' element
    xml:
      path: '{{ cucm_primary_node.answer_file_path }}'
      xpath: /PlatformData/Version
      value: 11.5.1
      pretty_print: yes
  
  - include_tasks: answer-file-base-element.yml
    loop: "{{ c1_template_platform_data_children }}"

  - name: Add a 'CertX509' element to the 'PlatformData' element
    xml:
      path: '{{ cucm_primary_node.answer_file_path }}'
      xpath: /PlatformData/CertX509
      pretty_print: yes

  - include_tasks: answer-file-base-element.yml
    loop: "{{ c1_template_certx509_children }}"

  - name: Copy XML file to common the folder with the following playbook
    copy:
      src: '{{ cucm_primary_node.answer_file_path }}'
      dest: '/images/{{ cucm_primary_node_common.answer_file_prefix }}-platformConfig.xml'
      force: no

  - name: Recursively remove Client's directory
    file:
      path: 'temp/{{ customer_name }}'
      state: absent