---

- hosts: localhost
  tasks:
  
  # Validate that the required datastore(s) are created
  - include_tasks: datastore-validation.yml
    loop: "{{ clones_parameters }}"
    when: folders_parameters is defined
  
