---

- hosts: localhost
  tasks:
  - name: Include parameters as variables
    include_vars: common-parameters.yml
    when: (call_from_tower is undefined or call_from_tower|bool == False)
    register: included_common_parameters
  
  - name: Include clones parameters
    include_vars: clones_parameters.yml
    when: (call_from_tower is undefined or call_from_tower|bool == False)
    register: included_clones_parameters
  
  - name: Include folders parameters
    include_vars: folders_parameters.yml
    when: (call_from_tower is undefined or call_from_tower|bool == False)
    register: included_folders_parameters
  
  - name: include answer-file-c1-parameters
    include_vars: answer-file-c1-parameters.yml
    when: (call_from_tower is undefined or call_from_tower|bool == False)

  - include_tasks: create-folders.yml
    loop: "{{ folders_parameters }}"
    when: folders_parameters is defined
  
  - include_tasks: answer-file-creation-cucm.yml
    when: clones_parameters is defined

  - include_tasks: floppy-disk-creation.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined
  
  - include_tasks: answer-files-cleanup.yml
    when: clones_parameters is defined

  - include_tasks: clone.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined

  - include_tasks: floppy-drive-creation.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined

  - include_tasks: poweroff.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined