---

- hosts: localhost
  tasks:
  
  # Validate that the required datastore(s) are created
  - include_tasks: datastore-validation.yml
    loop: "{{ clones_parameters }}"
    when: folders_parameters is defined
  
  # Create Sub-Folders to place the new upcoming VMs
  - include_tasks: folders/folders-creation.yml
    loop: "{{ folders_parameters }}"
    when: folders_parameters is defined
  
  # Create Answer Files
  - include_tasks: answer-file/answer-file-creation-cucm.yml
    when: clones_parameters is defined
  
  # Create Floppy Disks
  - include_tasks: floppy-disk/floppy-disk-creation.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined
  
  #Cleanup Answer Files
  - include_tasks: answer-file/answer-file-cleanup.yml
    when: clones_parameters is defined
  
  # Clone Templates to VMs
  - include_tasks: clone.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined
  
  # Power Off the Created VMs
  - include_tasks: poweroff.yml
    loop: "{{ clones_parameters }}"
    when: clones_parameters is defined